site_name: Unity User Documentation
# nav:
#  - Home: "index.md"
#  - Set Up Unity Project: "setup-project.md"
#  - Create A Simple 2D Game: "make-game.md"
#  - Create A Menu & Set Up Transitions: "make-menus.md"
#  - Build And Upload Your Game: "build-game.md"
#  - Troubleshooting: "troubleshooting.md"
#  - Glossary: "glossary.md"

repo_url: https://github.com/Mcitang/User-Documentation
repo_name: Mcitang/User-Documentation

theme:
  name: material

  features:
    # Groups pages under headers in the sidebar
    # - navigation.sections

    # Adds a back to top button
    - navigation.top 

    # Integrates floating right table of contents to the headers floating left
    - toc.integrate

    # Allow for us to annotate code like // (1) and // (2)
    - content.code.annotate

    # Adds a copy to clipboard button to the code blocks
    - content.code.copy

  icon:
    repo: fontawesome/brands/github

  font:
    text: Merriweather Sans
    code: Red Hat Mono
  palette:
    # Light mode
    - media: "(prefers-color-scheme: light)"
      scheme: default
      primary: black
      accent: deep purple
      toggle:
        icon: material/weather-sunny
        name: Dark mode

    # Dark mode
    - media: "(prefers-color-scheme: dark)"
      scheme: slate
      primary: blue grey
      accent: light blue
      toggle:
        icon: material/weather-night
        name: Light mode

markdown_extensions:
  # Allows CSS Customization
  - attr_list
  # Emojis
  - pymdownx.emoji:
      emoji_index: !!python/name:material.extensions.emoji.twemoji
      emoji_generator: !!python/name:material.extensions.emoji.to_svg
      
copyright: Copyright &copy; 2021 - Matthew Tang, Gustavo Rodriguez
