site_name: Unity User Documentation
site_url: https://mcitang.github.io/User-Documentation/

# Using it to override the page order
nav:
 - Home: "index.md"
 - Install Unity Editor: "install-editor.md"
 - Navigate Editor: "navigate-editor.md"
 - Set Up Unity Project: "setup-project.md"
 - Create A Simple 2D Game: "make-game.md"
 - Create A Menu & Set Up Transitions: "make-menus.md"
 - Build And Upload Your Game: "build-game.md"
 - Troubleshooting: "troubleshooting.md"
 - Glossary: "glossary.md"
#  - Styleguide (REMOVE BEFORE DUE DATE): "styleguide.md"

repo_url: https://github.com/Mcitang/User-Documentation
repo_name: Mcitang/User-Documentation
  

theme:
  name: material

  features:
    # Groups pages under headers in the sidebar
    # - navigation.sections

    # Adds a back to top button
    - navigation.top 

    # Integrates floating right table of contents to the headers floating left
    - toc.integrate

    # Allow for us to annotate code like // (1) and // (2)
    - content.code.annotate

    # Adds a copy to clipboard button to the code blocks
    - content.code.copy

    # Stops the page from fully reloading
    # - navigation.instant

    # Adds a next page and previous page footer
    - navigation.footer

  icon:
    repo: fontawesome/brands/github

  font:
    text: Inter
    code: Fira Code
  palette:
    # Light mode
    - media: "(prefers-color-scheme: light)"
      scheme: default
      primary: black
      accent: indigo
      toggle:
        icon: material/weather-sunny
        name: Dark mode

    # Dark mode
    - media: "(prefers-color-scheme: dark)"
      scheme: slate
      primary: grey
      accent: indigo
      toggle:
        icon: material/weather-night
        name: Light mode

markdown_extensions:
  # Adds definition tooltips to glossary words (defined at the bottom of markdown file)
  - abbr

  # Overrides the TOC div header and controls which header numbers to include
  - toc:
      title: In this page
      toc_depth: 3

  # Allows customizing CSS by using {: #id, .class, style="property: value;" }
  - attr_list

  # Emojis
  - pymdownx.emoji:
      emoji_index: !!python/name:material.extensions.emoji.twemoji
      emoji_generator: !!python/name:material.extensions.emoji.to_svg

    # Makes the colored boxes for DANGER, INFO, etc with !!! Supported types: https://squidfunk.github.io/mkdocs-material/reference/admonitions/#supported-types
  - admonition

  # Highlights codeblocks with pretty color, does code block annotations, and allows for code blocks in the admonition colored boxes
  - pymdownx.superfences

  # Easy dropdowns with ??? or ???+, with icon selected with these types: https://squidfunk.github.io/mkdocs-material/reference/admonitions/#supported-types
  - pymdownx.details

  # Wraps keys and shortcuts in UI keycaps. Syntax: ++ctrl+shift+s++
  - pymdownx.keys

  # Prevents underscores in the middle of words to accidentrally get italicized
  - pymdownx.betterem

  # Allows to group related content, including code blocks, into tabs
  - pymdownx.tabbed:
      alternate_style: true
      combine_header_slug: true

  # Used to show collaborator's suggestions for things like deletions and additions like so:
  # {--deletion suggest--}, {++addition suggest++} {==Highlighted comment==} {>> Comment <<}
  - pymdownx.critic

# CSS
extra_css:
  - stylesheets/styles.css
  - stylesheets/util.style.css
  # Pages
  - stylesheets/pages/glossary.style.css

# JavaScript
extra_javascript:
  - scripts/style.js
  # - scripts/glossary.js

copyright: Copyright &copy; 2026 - Matthew Tang, Gustavo Rodriguez
